
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;  
import java.sql.Statement;
import java.text.Normalizer;  
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RAFI
 */
public class Stok_barang extends javax.swing.JFrame {
    
    /**
     * Creates new form Stok_barang
     */
    public Stok_barang() {
        initComponents();
        data_barang();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
        
    private Connection conn = new Koneksi().Connect();
    private DefaultTableModel tabmodel;
    
    void reset() {
        txt_Npembeli.setText("");
        txt_merek.setText("");
        txt_Hbeli.setText("");
        txt_Hjual.setText("");
        txt_jumlah.setText("");
    }
    
    void data_barang () {
        String[] Data = {"Nama_Pembeli", "merek", "Harga Beli", "Harga Jual", "Jumlah"};
        tabmodel = new DefaultTableModel(null, Data);
        data_barang.setModel(tabmodel);
        String sql = "select' from data_barang";
        try {
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String Nama_Pembeli = hasil.getString("Nama_Pembeli");
                String merek = hasil.getString("merek");
                String harga_beli = hasil.getString("Harga Beli");
                String harga_jual = hasil.getString("Harga Jual");
                String jumlah = hasil.getString("Jumlah");
                String[] data = {Nama_Pembeli,merek,harga_beli,harga_jual,jumlah};
                tabmodel.addRow(data); 
            }
        } catch (SQLException ex) {
            Logger.getLogger(Normalizer.Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_Npembeli = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_merek = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_jumlah = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_Hbeli = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_Hjual = new javax.swing.JTextField();
        btn_insert = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        data_barang = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 204, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel1.setText("                                        HANDPHONE CELL");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 700, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Input Data");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 70, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("_______________________________________________________________________________________________________________________");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 720, 20));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Nama Pembeli");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, 30));

        txt_Npembeli.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(txt_Npembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 160, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Merek");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 130, 30));

        txt_merek.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(txt_merek, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 160, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Jumlah");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 130, 30));

        txt_jumlah.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(txt_jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 160, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Harga Beli");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 130, 30));

        txt_Hbeli.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(txt_Hbeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 160, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Harga Jual");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 130, 30));

        txt_Hjual.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(txt_Hjual, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 160, 30));

        btn_insert.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_insert.setText("Insert");
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });
        jPanel1.add(btn_insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 100, 30));

        btn_ubah.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 100, 30));

        btn_hapus.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        jPanel1.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 100, 30));

        btn_simpan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 100, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Data Barang");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 90, 20));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("_______________________________________________________________________________________________________________________");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 720, 20));

        data_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama_Pembeli", "merek", "Harga Beli", "Harga Jual", "Jumlah"
            }
        ));
        data_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                data_barangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(data_barang);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 390, 710, 260));

        jLabel2.setBackground(new java.awt.Color(153, 255, 153));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 720, 300));

        jLabel10.setBackground(new java.awt.Color(153, 255, 153));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setOpaque(true);
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 720, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed
        String sql = "insert into stok_barang values(?,?,?,?,?)";
        if (txt_Npembeli.getText().isEmpty() || txt_merek.getText().isEmpty() || txt_Hbeli.getText().isEmpty() || txt_Hjual.getText().isEmpty() || txt_jumlah.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data anda belum lengkap\nSilahkan melengkapinya terlebih dahulu");
        } else {
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, txt_Npembeli.getText());
                stat.setString(2, txt_merek.getText());
                stat.setString(3, txt_Hbeli.getText());
                stat.setString(4, txt_Hjual.getText());
                stat.setInt(5, Integer.parseInt(txt_jumlah.getText()));
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Data gagal disimpan");
            }
            reset();
            txt_Npembeli.requestFocus();
            data_barang();
        }
    }//GEN-LAST:event_btn_insertActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        if (data_barang.getSelectedRow() == -1) {
            if (data_barang.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Data Barang Kosong");
            } else {
                JOptionPane.showMessageDialog(null, "Pilih Data yang akan diubah");
            }
        } else {
            String sql = "update stok_barang set merek = '" + txt_merek.getText() + "',harga_jual = '" + txt_Hjual.getText() + "',harga_beli ='" + txt_Hbeli.getText() + "',jumlah ='" + txt_jumlah.getText() + "' WHERE nama_pembeli ='" + txt_Npembeli.getText() + "'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.execute();
                JOptionPane.showMessageDialog(null, "Data berhasil di Ubah");
                reset();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Perubahan Data Gagal");
            }
            data_barang();
        }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        String sqlbarang = "delete from stok_barang where nama_pembeli = '" + data_barang.getValueAt(data_barang.getSelectedRow(), 0).toString() + "'";
        if (data_barang.getSelectedRow() == -1) {
            if (data_barang.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Tidak ada data dalam tabel");
            } else {
                JOptionPane.showMessageDialog(null, "Pilih Data Yang akan dihapus");
            }
        } else {
            try {
                PreparedStatement stat = conn.prepareStatement(sqlbarang);
                stat.execute();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Data tidak berhasil dihapus");
            }
            data_barang();
            reset();
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        DefaultTableModel model = (DefaultTableModel) data_barang.getModel();
        model.addRow (new Object[] {txt_Npembeli.getText(), txt_merek.getText(), txt_Hbeli.getText(), txt_Hjual.getText(), txt_jumlah.getText()});
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void data_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data_barangMouseClicked
        String Nama_Pembeli = data_barang.getValueAt(data_barang.getSelectedRow(), 0).toString();
        String merek = data_barang.getValueAt(data_barang.getSelectedRow(), 1).toString();
        String harga_beli = data_barang.getValueAt(data_barang.getSelectedRow(), 2).toString();
        String harga_jual = data_barang.getValueAt(data_barang.getSelectedRow(), 3).toString();
        String jumlah = data_barang.getValueAt(data_barang.getSelectedRow(), 4).toString();
        txt_Npembeli.setText(Nama_Pembeli);
        txt_merek.setText(merek);
        txt_Hbeli.setText(harga_beli);
        txt_Hjual.setText(harga_jual);
        txt_jumlah.setText(jumlah);
    }//GEN-LAST:event_data_barangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stok_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stok_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stok_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stok_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stok_barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_insert;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JTable data_barang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_Hbeli;
    private javax.swing.JTextField txt_Hjual;
    private javax.swing.JTextField txt_Npembeli;
    private javax.swing.JTextField txt_jumlah;
    private javax.swing.JTextField txt_merek;
    // End of variables declaration//GEN-END:variables
}
